name: Run a gradle/junit task and upload test reports
description: |
  Utilizes CycloneDX to generate a SBOM. This SBOM will then be archived and uploaded to Github.

inputs:
  gradle-properties:
    description: Content of a gradle.properties file that will be passed to the gradle runner.
    required: false
  gradle-project-path:
    description: |
      Gradle project path. For example: bff.
      Defaults to the root project.
    required: true
    default: "."
  gradle-dependencies-cache-key:
    description: Extra files to take into account for ~/.gradle/caches dependencies
    required: true
    default: |
      buildSrc/**/Dependencies.kt
      gradle/libs.versions.toml
  report-retention-days:
    description: Duration in days to preserve reports.
    required: true
    default: "5"
  working-directory:
    description: Relative path under $GITHUB_WORKSPACE where the root project is located.
    required: false
    default: "."

runs:
  using: composite
  steps:
    - name: Action context
      shell: bash
      id: context
      run: |
        working_directory=$(realpath ${{ inputs.working-directory }})
        gradle_project_directory=$(realpath ${{ inputs.working-directory }}/${{ inputs.gradle-project-path }})
        echo "::set-output name=working-directory::$working_directory"
        echo "::set-output name=bom-path::$gradle_project_directory/build/reports/bom.json"

    - name: Generate BOM
      uses: burrunan/gradle-cache-action@v1
      with:
        gradle-version: wrapper
        build-root-directory: ${{ steps.context.outputs.working-directory }}
        gradle-dependencies-cache-key: ${{ inputs.gradle-dependencies-cache-key }}
        arguments: -p ${{ inputs.gradle-project-path }} :cyclonedxBom
        properties: ${{ inputs.gradle-properties }}

    - name: Upload BOM
      uses: evryfs/sbom-dependency-submission-action@v0.0.13
      with:
        sbom-files: ${{ steps.context.outputs.bom-path }}

    - name: Archive BOM
      uses: actions/upload-artifact@v3
      if: "!cancelled()"
      with:
        name: bom.json
        retention-days: ${{ inputs.report-retention-days }}
        path: ${{ steps.context.outputs.bom-path }}
